# sudo-enabled Ubuntu Trusty
dist: trusty

# running each build in docker container - cause speed
sudo: false

language: python
python: "2.7"

branches:
  only:
  packer-base
env:
  global:
    - DIR_BIN=~/bin
    - DIR_TMP=~/tmp
    - PACKER_VERSION=1.1.3
    before_install:
  #- sudo apt-get -qq update
  - sudo apt install -y wget

install:

  # making dirs
  - mkdir -p ~/${DIR_BIN} ~/${DIR_TMP}

  # getting packer
  - wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -P ~/${DIR_TMP}
  - unzip ~/${DIR_TMP}/packer_${PACKER_VERSION}_linux_amd64.zip -d ~/${DIR_BIN}
  - ~/${DIR_BIN}/packer --version
  script:

  # validating packer
  - cd packer
  - ~/${DIR_BIN}/packer validate -var-file=variables.json.example reddit-app.json
  - ~/${DIR_BIN}/packer validate -var-file=variables.json.example reddit-db.json
  - cd ..
