---
- name: Install MongoDB
  hosts: all
  tags: db-tag
  become: true
  
  tasks:
   - name: Add an apt key by id from a keyserver
     apt_key:
       keyserver: keyserver.ubuntu.com
       id: EA312927
   - apt_repository:
       repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2    multiverse
       state: present
       filename: 'mongodb-org-3.2'
   - name:  Run the equivalent of "apt-get update" as a separate step
     apt:
      update_cache: yes
   - name: Install the package "MongoDB"
     apt:
       name: mongodb-org
       state: present


  handlers:
   - name: restart mongod
     service: name=mongod state=restarted
