---
- name: Install Ruby and Build
  hosts: all
  tags: app-tags
  become: true
  vars:
   db_host: 10.132.0.2
  tasks:
   
   - name: Install the package "Ruby-full"
     apt:
      name: ruby-full
      state: present
   - name: Install the package "Ruby-bundler"
     apt:
      name: ruby-bundler
      state: present
   - name: Install the package "Bulid"
     apt:
      name: build-essential
      state: present
